name = "Obsea"
uuid = "eed2f6fc-f52c-4a11-a9a7-2ef59169b3cd"
authors = ["Alister Trabattoni <alister.trabattoni@gmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
julia = "1.4"
Interpolations = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
